#!/bin/bash

encrypt() {
	for d in $(ls --color=none "$CONFDIR" | sort -n); do
                local dir="${CONFDIR}/${d}"
                for f in $(ls --color=none $dir | sort -n); do
                        local file="${dir}/${f}"
			[[ $file =~ .*enc$ ]] && \
				(echo -e "\nEncrypting $file" && \
				gpg --yes \
                                    --quiet \
                                    --recipient "$GPGKEY" \
                                    --encrypt "$file")
        	done;
	done;
}
