#!/bin/bash

cb() {
        local so="$(uname)"
        local command=$([[ "${so^^}" == 'LINUX' ]] && echo -n 'xclip -sel clip' || echo -n 'pbcopy')

        $command
}

pas() {
        pbpaste
}

2fa() {
	echo -n "$(oathtool -b --totp "$1")"
}

vaultgp() {
	bw get password "$1"
}

vault2fa() {
	local k=$(bw get item "$1" | \
		jq '.fields[] | select(.name == "2fa") | .value' | \
		sed 's/"//g')
	echo -n "$(2fa "$k")"
}

vaultq() {
        local QUERY="$1"
        bw list items --search "$QUERY" | jq .
}

vaultgu() {
        local ID="$1"
        local USER=$(bw get item "$ID" | jq .login.username | sed 's/"//g')
        echo -n "$USER"
}

vaultcustom() {
        local ID="$1"
        local FIELD="$2"
	local v=$(bw get item "$ID" | \
		jq ".fields[] | select(.name == \"$FIELD\") | .value" | \
		sed 's/"//g')
	echo -n "$v"
}

2facb() {
	2fa "$1" | cb
}

vaultgpcb() {
	vaultgp "$1" | cb
}

vault2facb() {
	vault2fa "$1" | cb
}

vaultgucb() {
	vaultgu "$1" | cb
}
